version: '3.9'

services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_TCP_PORT: 3307
      MYSQL_USER: application-user-docker
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: userdetails
      MYSQL_HOST: mysql
    volumes:
      - ./dbmysql/tables:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307
    build: ./dbmysql
  
  authenticator-api:
    container_name: authenticator
    build: ./
    environment:
      MYSQL_USER: application-user-docker
      MYSQL_PASSWORD: 123456
      MYSQL_DB: userdetails
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8086:8086
    tty: true
    command: sh -c "sleep 20 && go run ./main.go"
      
